
apiVersion: v1
kind: PersistentVolume
metadata:
  name: code
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/aka/website/code"
    
--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  name: settings
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/aka/website/settings"
    
--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: settings
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
