apiVersion: v1
kind: Service
metadata:
  name: aspnetservice
  namespace: default
spec:
  selector:
    app: aspnet
  ports:
  - port: 80
    name: http

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnet
  template:
    metadata:
      labels:
        app: aspnet
    spec:

      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: code

      containers:
      - name: aspnet
        workingDir: /var/www/website/aspnet/build
        image: mcr.microsoft.com/dotnet/aspnet:5.0
        command: [ "dotnet", "aspnetapp.dll"]

        volumeMounts:
        - name: code
          mountPath: /var/www/website

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

#mcr.microsoft.com/dotnet/sdk:5.0
#dotnet restore
#dotnet publish -c release -o /app --no-restore
