apiVersion: v1
kind: Service
metadata:
  name: nginxservice
  namespace: default
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    name: http

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:

      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: code
      - name: settings
        persistentVolumeClaim:
          claimName: settings

      containers:
      - name: nginx
        image: nginx:latest

        volumeMounts:
        - name: code
          mountPath: var/www/html
        - name: settings
          mountPath: etc/nginx/conf.d
          subPath: nginx/conf.d
        - name: settings
          mountPath: etc/nginx/nginx.conf
          subPath: nginx/nginx.conf

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
