apiVersion: v1
kind: Service
metadata:
  name: nodeservice
  namespace: default
spec:
  selector:
    app: node
  ports:
  - port: 80
    name: http

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:

      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: code

      containers:
      - name: node
        image: node:latest
        command: [ "node", "var/www/website/nodejs"]

        volumeMounts:
        - name: code
          mountPath: /var/www/website

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

