apiVersion: v1
kind: Service
metadata:
  name: haproxyservice
  namespace: default
spec:
  selector:
    app: haproxy
  ports:
  - port: 80
    name: http

---

apiVersion: v1
kind: Service
metadata:
  name: phpservice
  namespace: default
spec:
  selector:
    app: php
  ports:
  - port: 9000
    name: php-port

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:

      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: code
      - name: settings
        persistentVolumeClaim:
          claimName: settings

      containers:
      - name: php
        image: php:8-fpm

        volumeMounts:
        - name: code
          mountPath: /var/www/website

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:

      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: code
      - name: settings
        persistentVolumeClaim:
          claimName: settings

      containers:
      - name: haproxy
        image: haproxy:latest

        volumeMounts:
        - name: settings
          mountPath: /usr/local/etc/haproxy/haproxy.cfg
          subPath: php/haproxy/haproxy.cfg

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
