apiVersion: v1
kind: Service
metadata:
  name: traefikservice
  namespace: default
spec:
  externalIPs:
    - '192.168.178.23'
  selector:
    app: traefik
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  - port: 8080
    name: admin

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
    
      volumes:
      - name: code
        persistentVolumeClaim:
          claimName: code
      - name: settings
        persistentVolumeClaim:
          claimName: settings

      containers:
      - name: traefik
        image: traefik:latest
        args:
          - --configfile=app/traefik.yaml

        volumeMounts:
        - name: settings
          mountPath: /app
          subPath: traefik

        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
